[features]
seeds = false
skip-lint = false
[programs.localnet]
my_anchor_app = "CVgxvZ7TwkyAuE8XY8ac35HkUNyAgBjgC5gyN2NA3TTA"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/anja/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
[toolchain]
anchor_version = "0.32.1"
[test]
startup_wait = 8000   # milliseconds (8s). Bump to 15000 if needed.
